# Setup which custom fields from Issue/Project should be hierarchically available for the TimeEntry record

# The CustomFields #internal_name will be prefixed with model_name
# E.g. {project => {fields => [invoice_reference] }} will return 'project_invoice_reference'

# All attributes under the name key will be passed directly to the CustomField instance when created or updated
#project:
#  fields:
#    customer_invoice_reference:
#      # this will create the ProjectCustomField `project_customer_invoice_reference`
#      # these attributes are directly passed to the created CustomFieldEntry
#      field_format: string
#      is_requiered: true
#      regexp: /[A-Za-z0-9]{1,}/
#issue:
#  fields:
#    customer:
#      field_format: int
