# List all fields that should be covered by hierarchy custom fields
# Each entry creates three fields:
#   'issue_customer_invoice_reference'      as IssueCustomField
#   'project_customer_invoice_reference'    as PrjoectCustomField
#   'time_entr_customer_invoice_reference'  as TimeEntryCustomField
#
# All options (expect :fallbacks) given are directly passed to the created time entry.
# !! 'internal_name' field is automatically created and MUST NOT be changed/overwritten

# customer_invoice_reference:
#   field_format: string
#   searchable: true
